# Generated by Django 5.0.6 on 2025-03-16 10:45

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flattened', models.TextField()),
                ('nplayers', models.IntegerField()),
                ('extra_data', models.TextField()),
                ('ready', models.BooleanField()),
                ('code', models.CharField(max_length=9)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('primary_color', models.CharField(default='#03A5FC', max_length=7)),
                ('secondary_color', models.CharField(default='#FC0B03', max_length=7)),
                ('tertiary_color', models.CharField(default='#FAD102', max_length=7)),
                ('quaternary_color', models.CharField(default='#02FABC', max_length=7)),
                ('faint_primary_color', models.CharField(default='#ABCDEF', max_length=7)),
                ('faint_secondary_color', models.CharField(default='#D6C1C1', max_length=7)),
                ('superfaint_primary_color', models.CharField(default='#D5E6F7', max_length=7)),
                ('superfaint_secondary_color', models.CharField(default='#EBE0E0', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('affrm_color', models.CharField(default='#639919', max_length=7)),
                ('afrm2_color', models.CharField(default='#F5E911', max_length=7)),
                ('neutral_color', models.CharField(default='#777777', max_length=7)),
                ('negative_color', models.CharField(default='#C94040', max_length=7)),
                ('font_family', models.CharField(default='Helvetica', max_length=30)),
                ('heading_font', models.CharField(default='Helvetica', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_index', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
