# Generated by Django 5.0.6 on 2025-03-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='A user of Adamant Games.', max_length=300),
        ),
    ]
