# Generated by Django 5.0.6 on 2025-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_game_tli_alter_game_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='public_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='public_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hashed_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
