# Generated by Django 5.0.6 on 2025-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_public_join_game_public_view_player_hashed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
