# Generated by Django 5.0.6 on 2025-03-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nmoves',
            field=models.IntegerField(default=-2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='ready',
            field=models.IntegerField(),
        ),
    ]
