# Generated by Django 5.0.6 on 2025-03-28 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_nmoves_alter_game_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='made_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
