# Generated by Django 5.0.6 on 2025-09-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_user_background_highlight_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faint_quaternary_color',
            field=models.CharField(default='#80FCDD', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='faint_tertiary_color',
            field=models.CharField(default='#FCE880', max_length=7),
        ),
    ]
